modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="lastdawn"
version="1.0.0"
displayName="LastDawn"
authors="Givler"
description='''Описание вашего мода.'''

[[dependencies.lastdawn]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.lastdawn]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
